name = "HomogeneousVectors"
uuid = "5d3f8266-9186-4afd-be5f-84c55396a2a7"
authors = ["Tamás Cserteg <csertegt@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
